name: Android Build

on: 
  push:
  workflow_dispatch:

env:
  ANDROID_NDK_VERSION: r25b

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ninja-build \
            libglib2.0-dev \
            libgirepository1.0-dev \
            valac \
            python3-pip
          pip install meson
          
      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip
          unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux.zip
          echo "ANDROID_NDK_ROOT=$PWD/android-ndk-${ANDROID_NDK_VERSION}" >> $GITHUB_ENV
          
      - name: Apply Android fix
        run: |
          cd subprojects/frida-core
          curl -L https://raw.githubusercontent.com/frida/frida-core/725286c9cccbc74f2e80b7f1e15f3e17134e4ba7/lib/payload/cloak.vala -o lib/payload/cloak.vala
          cd ../..
          
      - name: Build frida-server for Android arm64
        run: |
          export PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          ./configure --host=android-arm64 --enable-server
          make
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frida-server-android-arm64-patched
          path: build/frida-android-arm64/bin/frida-server